name: Ubuntu LTS
on: 
    workflow_dispatch:
    schedule:
        - cron: '0 0 * * *'
jobs:
  buildOnLTS:
    runs-on: ubuntu-20.04
    container:
      image: ubuntu:jammy
    steps:
    - name: Checkout sources
      uses: actions/checkout@v4
    - name: Get Dependencies
      run: |
        apt update
        apt install -y software-properties-common g++ make cmake ninja-build wget rsync build-essential libglib2.0-0 libgl1-mesa-dev file
    - name: Install Qt
      run: |
        apt install -y qt6-base-dev qt6-multimedia-dev qt6-image-formats-plugins qt6-5compat-dev
    - name: Install Vulkan
      run: |
          apt install -y libvulkan-dev
    - name: Build AnimeEffects
      shell: bash
      run: |
        echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
        cmake -S . -B build -G "Ninja Multi-Config"
        cmake --build build --config Release --install --prefix "/usr/appdir"
        dir
        mkdir -p appdir/usr/bin
        dir
        cp AnimeEffects appdir/usr/bin
        dir
        cp -R data appdir/usr/bin/data
        dir
        find appdir/
        export APPIMAGE_EXTRACT_AND_RUN=1
        wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
        if [[ "$RELEASE_VERSION" != "" ]]; then export VERSION=$RELEASE_VERSION;fi
        chmod a+x linuxdeployqt-continuous-x86_64.AppImage
        ./linuxdeployqt-continuous-x86_64.AppImage appdir/usr/share/applications/*.desktop -extra-plugins=imageformats -appimage -verbose=2
    - name: Github Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: AnimeEffects 
        path: |
          AnimeEffects-x86_64.AppImage
          /__w/AnimeEffects/AnimeEffects/appdir/AnimeEffects.desktop

