name: MacOS
on: workflow_dispatch
      
jobs:
  buildMac:
    runs-on: macOS-latest
    steps:
    - name: checkout sources
      uses: actions/checkout@v2
    - name: setup Homebrew
      shell: bash
      run: |
        export HOMEBREW_NO_AUTO_UPDATE=1 && export HOMEBREW_NO_INSTALL_CLEANUP=1 && rm '/usr/local/bin/2to3' && brew update
        HOMEBREW_VERBOSE_USING_DOTS=1 brew reinstall --verbose qt5
    - name: build AnimeEffects
      shell: bash
      run: |
        export PATH="/usr/local/opt/qt@5/bin:$PATH"
        qmake src/AnimeEffects.pro CONFIG+=release PREFIX=/usr
        make -j$(nproc)
        make INSTALL_ROOT=appdir install
        mkdir -p appdir/usr/bin
        cp -R data appdir/usr/bin/data
        find appdir/
        mkdir -p appdir/usr/lib
        macdeployqt AnimeEffects.app
        wget https://raw.githubusercontent.com/arl/macdeployqtfix/master/macdeployqtfix.py && chmod a+x macdeployqtfix.py
        ./macdeployqtfix.py AnimeEffects.app /usr/local/Cellar/qt/*/
        zip -r AnimeEffects.zip AnimeEffects.app
        
    - name: GitHub Releases
      uses: svenstaro/upload-release-action@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: AnimeEffects.zip
        tag: ${{ github.ref }}
