name: Ubuntu LTS
on: push

jobs:
  buildOnFocal:
    runs-on: ubuntu-20.04
    container:
      image: ubuntu:latest
    steps:
    - name: checkout sources
      uses: actions/checkout@v2

    - name: add build dependencies
      run: |
        apt update
        apt install -y software-properties-common g++ make wget rsync
        apt-get update
        apt install -y build-essential libglib2.0-0 qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools libgl1-mesa-dev 
        
    - name: build AnimeEffects
      shell: bash
      run: |
        echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
        qmake src/AnimeEffects.pro -r CONFIG+=release PREFIX=/usr
        make -j$(nproc)
        make INSTALL_ROOT=appdir install
        mkdir -p appdir/usr/bin
        cp AnimeEffects appdir/usr/bin
        cp -R data appdir/usr/bin/data
        find appdir/
        export APPIMAGE_EXTRACT_AND_RUN=1
        wget -c -nv "https://github.com/gcmcnutt/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
        if [[ "$RELEASE_VERSION" != "" ]]; then export VERSION=$RELEASE_VERSION;fi
        chmod a+x linuxdeployqt-continuous-x86_64.AppImage
        ./linuxdeployqt-continuous-x86_64.AppImage appdir/usr/share/applications/*.desktop -extra-plugins=imageformats -appimage -verbose=2

    - name: GitHub Releases
      uses: fnkr/github-action-ghr@v1.3
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GHR_PATH: AnimeEffects-x86_64.AppImage
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

